package com.forgebrain.backend.services;

import com.forgebrain.backend.ai.AiGateway;
import com.forgebrain.backend.ai.AiGatewayResult;
import com.forgebrain.backend.ai.AiPromptExecution;
import com.forgebrain.backend.exceptions.AiGatewayException;
import com.forgebrain.backend.exceptions.ContentGenerationException;
import com.forgebrain.backend.models.Scene;
import com.forgebrain.backend.models.Script;
import com.forgebrain.backend.models.Storyboard;
import com.forgebrain.backend.models.VisualPlan;
import com.forgebrain.backend.shared.ConfidenceLevel;
import com.forgebrain.backend.shared.ConfidenceNotes;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * AI Gateway-backed {@link VisualDirectorService}: calls {@link AiGateway} to direct each
 * storyboard scene's visual treatment (see {@link VisualDirectorPromptBuilder}) and assembles
 * every deterministic field ({@code sceneId}, {@code durationSeconds}) by zipping the response's
 * scenes array against {@code storyboard.scenes()} by index — the model never invents scene
 * identity or timing.
 *
 * <p>Falls back to {@link VisualDirectorServiceImpl} whenever the AI Gateway can't produce a
 * usable result — see {@link AiGatewayException}. The fallback is a real, exercised code path,
 * not a stub: this is the only path this sandbox can take without live GCP credentials.
 */
@Component
public class VertexAiVisualDirectorServiceImpl implements VisualDirectorService {

    private static final Logger log = LoggerFactory.getLogger(VertexAiVisualDirectorServiceImpl.class);
    private static final String VISUAL_PLAN_VERSION = "1.0.0-vertex-ai";
    private static final String PROMPT_NAME = "visual-director";

    private final AiGateway aiGateway;
    private final VisualDirectorServiceImpl fallback;

    public VertexAiVisualDirectorServiceImpl(AiGateway aiGateway) {
        this.aiGateway = aiGateway;
        this.fallback = new VisualDirectorServiceImpl();
    }

    @Override
    public VisualPlan generateVisualPlan(Script script, Storyboard storyboard) {
        try {
            return generateViaAiGateway(script, storyboard);
        } catch (AiGatewayException e) {
            if (e.reason() == AiGatewayException.Reason.CONFIGURATION) {
                log.info("AI gateway unavailable for visual direction ({}); falling back to heuristic visual plan"
                        + " for topic '{}'.", e.getMessage(), storyboard.topicId());
            } else {
                log.warn("AI gateway visual director call failed for topic '{}'; falling back to heuristic visual"
                        + " plan.", storyboard.topicId(), e);
            }
            aiGateway.recordFallbackUsed(PROMPT_NAME);
        }
        return fallback.generateVisualPlan(script, storyboard);
    }

    private VisualPlan generateViaAiGateway(Script script, Storyboard storyboard) {
        List<Scene> scenes = storyboard.scenes();
        String promptText = VisualDirectorPromptBuilder.build(script, storyboard);
        AiGatewayResult<VertexAiVisualPlanContent> result = aiGateway.execute(new AiPromptExecution<>(PROMPT_NAME,
                promptText, Map.of("topic_id", storyboard.topicId()), VertexAiVisualPlanContent.class,
                content -> validate(content, scenes.size())));
        VertexAiVisualPlanContent content = result.content();

        List<VisualPlan.VisualScenePlan> visualScenes = new ArrayList<>();
        for (int i = 0; i < scenes.size(); i++) {
            Scene scene = scenes.get(i);
            VertexAiVisualScenePlan scenePlan = content.scenes().get(i);
            visualScenes.add(new VisualPlan.VisualScenePlan(
                    scene.sceneId(),
                    scenePlan.scenePrimitive(),
                    scenePlan.hookIntent(),
                    scenePlan.visualGoal(),
                    scenePlan.composition(),
                    scenePlan.cameraMotion(),
                    scenePlan.backgroundStyle(),
                    scenePlan.foregroundElements() != null ? scenePlan.foregroundElements() : List.of(),
                    scenePlan.textOverlay(),
                    scenePlan.codeBlockHint(),
                    scenePlan.diagramType(),
                    scenePlan.imagePrompt(),
                    scenePlan.motionCue(),
                    scenePlan.transitionIn(),
                    scenePlan.transitionOut(),
                    scene.duration()
            ));
        }

        List<String> flagged = List.of("Generated by Vertex AI (" + result.modelId() + ", via the AI Gateway's"
                + " 'visual-director' prompt) from storyboard_version=" + storyboard.storyboardVersion() + ".");

        return new VisualPlan(
                storyboard.topicId(),
                storyboard.topicTitle(),
                visualScenes,
                content.thumbnailBrief(),
                new ConfidenceNotes(ConfidenceLevel.HIGH, flagged, List.of()),
                VISUAL_PLAN_VERSION,
                Instant.now(),
                storyboard.storyboardVersion()
        );
    }

    private void validate(VertexAiVisualPlanContent content, int expectedSceneCount) {
        if (isBlank(content.thumbnailBrief()) || content.scenes() == null
                || content.scenes().size() != expectedSceneCount) {
            throw new ContentGenerationException("visual-director",
                    "AI gateway visual plan response is missing a thumbnail brief, or its scenes array (size "
                            + (content.scenes() == null ? "null" : content.scenes().size())
                            + ") does not match the storyboard's scene count (" + expectedSceneCount + "): " + content);
        }
        for (VertexAiVisualScenePlan scenePlan : content.scenes()) {
            if (scenePlan.scenePrimitive() == null || scenePlan.composition() == null
                    || isBlank(scenePlan.visualGoal()) || scenePlan.transitionIn() == null
                    || scenePlan.transitionOut() == null) {
                throw new ContentGenerationException("visual-director",
                        "AI gateway response has a scene visual plan missing required fields: " + scenePlan);
            }
        }
    }

    private static boolean isBlank(String text) {
        return text == null || text.isBlank();
    }
}
